import Image from 'next/image'
import Link from "next/link";
import Head from "next/head";
import SocialButton from './components/button/SocialButton';
import Github from "../public/github.svg";
import Instagram from "../public/instagram.svg";
import Twitter from "../public/twitter.svg";
import Linkedin from "../public/linkedin.svg";
import ProjectPreview from './components/card/ProjectPreview';

export default function Home() {


  return (
    <div>
      <Head>
        <title>GitCarrot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="grid grid-cols-1 lg:grid-cols-[2fr_1fr] gap-4 mb-4">
        <div className="bg-zinc-200 h-[30rem] rounded-3xl p-10 flex flex-col gap-16 bg-[url('/gradient-bg.jpg')] bg-cover">
          <h1 className="text-4xl font-semibold">
            Hello, I am a GitCarrot.
          </h1>
          <p className="flex-1">
          I am studying for a B.S. in Computer Science in the Department of Information and Computer Sciences at the University of Hawaii. Focused on the backend service using spring boot. I expect to graduate in Spring, 2024.
          </p>
          <div className="flex flex-col lg:flex-row items-center gap-4 justify-self-end">
            <button className="bg-black text-white font-medium py-3 px-12 rounded-full w-60 lg:w-auto">
              Contact me
            </button>
            <div className="flex items-center gap-4">
              <SocialButton bgColor="dribbble">
                <Link href="//github.com/gitCarrot">
                  <Github className="w-5 h-5" />
                </Link>
              </SocialButton>
              {/* <SocialButton bgColor="twitter">
                <Twitter className="w-5 h-5" />
              </SocialButton> */}
              <SocialButton bgColor="linkedin">
                <Link href="//www.linkedin.com/in/honggun-jeon-ics/">
                  <Linkedin className="w-5 h-5" />
                </Link>
              </SocialButton>
              <SocialButton bgColor="instagram">
                <Instagram className="w-5 h-5" />
              </SocialButton>
            </div>
          </div>
        </div>
        <div className="h-[30rem] rounded-3xl p-8 bg-[url('/ME.jpg')] bg-center bg-contain bg-no-repeat" />
      </section>

      <section className="grid grid-cols-1 lg:grid-cols-2 gap-4 my-4">
      <Link href="/projects">
        <ProjectPreview
          name="Projects"
          description="Team / Personal Projects"
          imageUrl="/web.png"
          bgColor="#313442"
          dark
        />
      </Link>
      <Link href="/articles">
        <ProjectPreview
          name="Articles"
          description="IT technique & engineering"
          imageUrl="/algorithm.png"
          bgColor="#685cdd"
          dark
        />
      </Link>
        <ProjectPreview
          name="Data Engineering"
          description="Increase user engagement"
          imageUrl="/project-3.png"
        />
        <ProjectPreview
          name="Project Dashboard"
          description="Project management app"
          imageUrl="/p"
          bgColor="#4e4e56"
          dark
        />
        <ProjectPreview
          name="App"
          description="To be Continue"
          imageUrl=""
          bgColor="#171717"
          dark
        />
        <ProjectPreview
          name="Crypto"
          description="To be Continue"
          imageUrl="/project-3.png"
        />
      </section>



    </div>
  )
}
